import "./globals.css";
import type { Metadata } from "next";
import { Varela_Round } from "next/font/google";
import Hero from "@/components/Hero";
import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import Mouse from "@/components/mouseFollower/MouseFollower";
import UpdateFollower from "@/components/mouseFollower/UpdateFollower";

const varelaRound = Varela_Round({
  variable: "--font-varela-round",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${varelaRound.variable} antialiased`}>
        <Mouse />

        <UpdateFollower
          mouseOptions={{
            backgroundColor: "white",
            zIndex: 999,
            followSpeed: 1.5,
          }}
        >
          <Navbar />
          <Hero />
        </UpdateFollower>

        <UpdateFollower
          mouseOptions={{
            backgroundColor: "black",
            zIndex: 999,
            followSpeed: 1.5,
          }}
        >
          <main>{children}</main>
          <Footer />
        </UpdateFollower>
      </body>
    </html>
  );
}
